// Generated by TanStack Router (stub for typecheck)
// This file is auto-generated when the dev server runs

import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router'

// Import route components
import { Route as RootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as BlogIndexRoute } from './routes/blog/index'
import { Route as BlogSlugRoute } from './routes/blog/$slug'

// Create the route tree
const rootRoute = RootRoute

const indexRoute = IndexRoute

const blogIndexRoute = BlogIndexRoute

const blogSlugRoute = BlogSlugRoute

export const routeTree = rootRoute.addChildren([
  indexRoute,
  blogIndexRoute.addChildren([blogSlugRoute]),
])

// Declare the router types
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof RootRoute
    }
    '/blog/': {
      preLoaderRoute: typeof BlogIndexRoute
      parentRoute: typeof RootRoute
    }
    '/blog/$slug': {
      preLoaderRoute: typeof BlogSlugRoute
      parentRoute: typeof BlogIndexRoute
    }
  }
}
