/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as GraphIndexRouteImport } from './routes/graph/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TagTagIdRouteImport } from './routes/tag/$tagId'
import { Route as ContentSlugRouteImport } from './routes/content/$slug'
import { Route as BlogWikiRouteImport } from './routes/blog/wiki'
import { Route as BlogOpinionRouteImport } from './routes/blog/opinion'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagIdRoute = TagTagIdRouteImport.update({
  id: '/tag/$tagId',
  path: '/tag/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentSlugRoute = ContentSlugRouteImport.update({
  id: '/content/$slug',
  path: '/content/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWikiRoute = BlogWikiRouteImport.update({
  id: '/blog/wiki',
  path: '/blog/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogOpinionRoute = BlogOpinionRouteImport.update({
  id: '/blog/opinion',
  path: '/blog/opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/opinion': typeof BlogOpinionRoute
  '/blog/wiki': typeof BlogWikiRoute
  '/content/$slug': typeof ContentSlugRoute
  '/tag/$tagId': typeof TagTagIdRoute
  '/blog/': typeof BlogIndexRoute
  '/graph/': typeof GraphIndexRoute
  '/wiki/': typeof WikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/opinion': typeof BlogOpinionRoute
  '/blog/wiki': typeof BlogWikiRoute
  '/content/$slug': typeof ContentSlugRoute
  '/tag/$tagId': typeof TagTagIdRoute
  '/blog': typeof BlogIndexRoute
  '/graph': typeof GraphIndexRoute
  '/wiki': typeof WikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/opinion': typeof BlogOpinionRoute
  '/blog/wiki': typeof BlogWikiRoute
  '/content/$slug': typeof ContentSlugRoute
  '/tag/$tagId': typeof TagTagIdRoute
  '/blog/': typeof BlogIndexRoute
  '/graph/': typeof GraphIndexRoute
  '/wiki/': typeof WikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brand'
    | '/blog/$slug'
    | '/blog/opinion'
    | '/blog/wiki'
    | '/content/$slug'
    | '/tag/$tagId'
    | '/blog/'
    | '/graph/'
    | '/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brand'
    | '/blog/$slug'
    | '/blog/opinion'
    | '/blog/wiki'
    | '/content/$slug'
    | '/tag/$tagId'
    | '/blog'
    | '/graph'
    | '/wiki'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brand'
    | '/blog/$slug'
    | '/blog/opinion'
    | '/blog/wiki'
    | '/content/$slug'
    | '/tag/$tagId'
    | '/blog/'
    | '/graph/'
    | '/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandRoute: typeof BrandRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogOpinionRoute: typeof BlogOpinionRoute
  BlogWikiRoute: typeof BlogWikiRoute
  ContentSlugRoute: typeof ContentSlugRoute
  TagTagIdRoute: typeof TagTagIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GraphIndexRoute: typeof GraphIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/': {
      id: '/graph/'
      path: '/graph'
      fullPath: '/graph/'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tagId': {
      id: '/tag/$tagId'
      path: '/tag/$tagId'
      fullPath: '/tag/$tagId'
      preLoaderRoute: typeof TagTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$slug': {
      id: '/content/$slug'
      path: '/content/$slug'
      fullPath: '/content/$slug'
      preLoaderRoute: typeof ContentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/wiki': {
      id: '/blog/wiki'
      path: '/blog/wiki'
      fullPath: '/blog/wiki'
      preLoaderRoute: typeof BlogWikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/opinion': {
      id: '/blog/opinion'
      path: '/blog/opinion'
      fullPath: '/blog/opinion'
      preLoaderRoute: typeof BlogOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandRoute: BrandRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogOpinionRoute: BlogOpinionRoute,
  BlogWikiRoute: BlogWikiRoute,
  ContentSlugRoute: ContentSlugRoute,
  TagTagIdRoute: TagTagIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  GraphIndexRoute: GraphIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
