ALTER TABLE "account" ALTER COLUMN "access_token_expires_at" SET DATA TYPE timestamp(3) USING "access_token_expires_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "refresh_token_expires_at" SET DATA TYPE timestamp(3) USING "refresh_token_expires_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "expires_at" SET DATA TYPE timestamp(3) USING "expires_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "verification" ALTER COLUMN "expires_at" SET DATA TYPE timestamp(3) USING "expires_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "verification" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "verification" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "feedback" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "feedback" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "feedback" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp(3) USING "deleted_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "game" ALTER COLUMN "game_date" SET DATA TYPE timestamp(3) USING "game_date"::timestamp(3);--> statement-breakpoint
ALTER TABLE "game" ALTER COLUMN "arrival_time" SET DATA TYPE timestamp(3) USING "arrival_time"::timestamp(3);--> statement-breakpoint
ALTER TABLE "game" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "game" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "game" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp(3) USING "deleted_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "invitation" ALTER COLUMN "expires_at" SET DATA TYPE timestamp(3) USING "expires_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "member" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "organization" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "player_contact_info" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "player_contact_info" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "player_contact_info" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp(3) USING "deleted_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "player" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "player" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "player" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp(3) USING "deleted_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "team_player" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "team_player" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "team_player" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp(3) USING "deleted_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "season" ALTER COLUMN "start_date" SET DATA TYPE timestamp(3) USING "start_date"::timestamp(3);--> statement-breakpoint
ALTER TABLE "season" ALTER COLUMN "end_date" SET DATA TYPE timestamp(3) USING "end_date"::timestamp(3);--> statement-breakpoint
ALTER TABLE "season" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "season" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "season" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp(3) USING "deleted_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "team_member" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "team" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "team" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "ban_expires" SET DATA TYPE timestamp(3) USING "ban_expires"::timestamp(3);--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "deleted_at" SET DATA TYPE timestamp(3) USING "deleted_at"::timestamp(3);