export const teamSeasonStats = {
  winningPercentage: 0.684,
  scoringOffense: 14.89,
  scoringDefense: 10.42,
  scoringMargin: 4.47,
  manUpOffense: 0.439,
  manDownDefense: 0.685,
  faceOffWinningPercentage: 0.512,
  shotPercentage: 0.353,
  groundBallsPerGame: 31.58,
  clearingPercentage: 0.892,
  pointsPerGame: 22.74,
  assistsPerGame: 7.84,
  savesPerGame: 11.63,
  turnoversPerGame: 14.84,
  causedTurnoversPerGame: 8.47,
};

export const lacrosseStats = {
  goals: 10,
  assists: 5,
  points: 15,
  shots: 15,
  shootingPercentage: 66.67, // computed
  shotsOnGoal: 10,
  shotsOnGoalPercentage: 66.67, // computed
  groundBalls: 5,
  causedTurnovers: 3,
  turnovers: 0,
  // goalie stats
  saves: 10,
  goalsAllowed: 6,
  savePercentage: 80, // computed
  // face off stats
  faceoffsWon: 10,
  faceoffsLost: 5,
  faceoffPercentage: 66.67, // computed
};

export const playerGameStats = {
  // info
  playerId: '1',
  teamId: '1',
  // general stats
  played: true,
  started: true,
  ...lacrosseStats,
};

export const game = {
  // game info
  date: '2023-01-01',
  opponentId: '1', // need pages for opponents
  teamScore: 11, //
  opponentScore: 9,
  homeAway: 'home', // home, away, neutral
  teamsStats: lacrosseStats,
  opponentStats: lacrosseStats,
  teamPlayerStats: new Array(8).fill(playerGameStats), // individual team player stats
  opponentPlayerStats: new Array(8).fill(playerGameStats), // individual opponent player stats
};

export const playerSeasonStats = {
  gamesPlayed: 8,
  gamesStarted: 8,
  ...lacrosseStats,
  gameByGameStats: new Array(8).fill(playerGameStats),
};

export const playerSeasonStatsMock: typeof playerSeasonStats = {
  gamesPlayed: 12,
  gamesStarted: 10,
  gameByGameStats: [
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: true,
      goals: 2,
      assists: 1,
      points: 3,
      shots: 4,
      shootingPercentage: 50.0,
      shotsOnGoal: 3,
      shotsOnGoalPercentage: 75.0,
      groundBalls: 2,
      causedTurnovers: 1,
      turnovers: 1,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: true,
      goals: 1,
      assists: 2,
      points: 3,
      shots: 5,
      shootingPercentage: 20.0,
      shotsOnGoal: 3,
      shotsOnGoalPercentage: 60.0,
      groundBalls: 3,
      causedTurnovers: 0,
      turnovers: 2,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: true,
      goals: 3,
      assists: 0,
      points: 3,
      shots: 6,
      shootingPercentage: 50.0,
      shotsOnGoal: 4,
      shotsOnGoalPercentage: 66.67,
      groundBalls: 1,
      causedTurnovers: 1,
      turnovers: 0,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: true,
      goals: 1,
      assists: 1,
      points: 2,
      shots: 3,
      shootingPercentage: 33.33,
      shotsOnGoal: 2,
      shotsOnGoalPercentage: 66.67,
      groundBalls: 2,
      causedTurnovers: 0,
      turnovers: 1,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: true,
      goals: 2,
      assists: 2,
      points: 4,
      shots: 4,
      shootingPercentage: 50.0,
      shotsOnGoal: 3,
      shotsOnGoalPercentage: 75.0,
      groundBalls: 1,
      causedTurnovers: 1,
      turnovers: 0,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: true,
      goals: 0,
      assists: 1,
      points: 1,
      shots: 2,
      shootingPercentage: 0,
      shotsOnGoal: 1,
      shotsOnGoalPercentage: 50.0,
      groundBalls: 2,
      causedTurnovers: 0,
      turnovers: 1,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: true,
      goals: 2,
      assists: 1,
      points: 3,
      shots: 5,
      shootingPercentage: 40.0,
      shotsOnGoal: 3,
      shotsOnGoalPercentage: 60.0,
      groundBalls: 0,
      causedTurnovers: 0,
      turnovers: 2,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: false,
      goals: 1,
      assists: 0,
      points: 1,
      shots: 2,
      shootingPercentage: 50.0,
      shotsOnGoal: 1,
      shotsOnGoalPercentage: 50.0,
      groundBalls: 1,
      causedTurnovers: 0,
      turnovers: 0,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: true,
      goals: 3,
      assists: 2,
      points: 5,
      shots: 6,
      shootingPercentage: 50.0,
      shotsOnGoal: 5,
      shotsOnGoalPercentage: 83.33,
      groundBalls: 1,
      causedTurnovers: 2,
      turnovers: 0,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: true,
      goals: 2,
      assists: 1,
      points: 3,
      shots: 4,
      shootingPercentage: 50.0,
      shotsOnGoal: 3,
      shotsOnGoalPercentage: 75.0,
      groundBalls: 1,
      causedTurnovers: 0,
      turnovers: 1,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: false,
      goals: 1,
      assists: 1,
      points: 2,
      shots: 3,
      shootingPercentage: 33.33,
      shotsOnGoal: 2,
      shotsOnGoalPercentage: 66.67,
      groundBalls: 1,
      causedTurnovers: 0,
      turnovers: 0,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
    {
      playerId: '1',
      teamId: '1',
      played: true,
      started: true,
      goals: 0,
      assists: 0,
      points: 0,
      shots: 1,
      shootingPercentage: 0,
      shotsOnGoal: 0,
      shotsOnGoalPercentage: 0,
      groundBalls: 0,
      causedTurnovers: 0,
      turnovers: 0,
      saves: 0,
      goalsAllowed: 0,
      savePercentage: 0,
      faceoffsWon: 0,
      faceoffsLost: 0,
      faceoffPercentage: 0,
    },
  ],
  goals: 18,
  assists: 12,
  points: 30,
  shots: 45,
  shootingPercentage: 40.0,
  shotsOnGoal: 30,
  shotsOnGoalPercentage: 66.67,
  groundBalls: 15,
  causedTurnovers: 5,
  turnovers: 8,
  saves: 0,
  goalsAllowed: 0,
  savePercentage: 0,
  faceoffsWon: 0,
  faceoffsLost: 0,
  faceoffPercentage: 0,
};

export const gamesMock: (typeof game)[] = [
  {
    date: '2024-09-05',
    opponentId: '2',
    teamScore: 12,
    opponentScore: 9,
    homeAway: 'home',
    teamsStats: {
      goals: 12,
      assists: 8,
      points: 20,
      shots: 32,
      shootingPercentage: 37.5,
      shotsOnGoal: 22,
      shotsOnGoalPercentage: 68.75,
      groundBalls: 28,
      causedTurnovers: 7,
      turnovers: 12,
      saves: 15,
      goalsAllowed: 9,
      savePercentage: 62.5,
      faceoffsWon: 12,
      faceoffsLost: 8,
      faceoffPercentage: 60.0,
    },
    opponentStats: {
      goals: 9,
      assists: 6,
      points: 15,
      shots: 24,
      shootingPercentage: 37.5,
      shotsOnGoal: 18,
      shotsOnGoalPercentage: 75.0,
      groundBalls: 22,
      causedTurnovers: 8,
      turnovers: 15,
      saves: 10,
      goalsAllowed: 12,
      savePercentage: 45.45,
      faceoffsWon: 8,
      faceoffsLost: 12,
      faceoffPercentage: 40.0,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
  {
    date: '2024-09-08',
    opponentId: '3',
    teamScore: 10,
    opponentScore: 11,
    homeAway: 'away',
    teamsStats: {
      goals: 10,
      assists: 7,
      points: 17,
      shots: 28,
      shootingPercentage: 35.71,
      shotsOnGoal: 18,
      shotsOnGoalPercentage: 64.29,
      groundBalls: 25,
      causedTurnovers: 5,
      turnovers: 14,
      saves: 12,
      goalsAllowed: 11,
      savePercentage: 52.17,
      faceoffsWon: 10,
      faceoffsLost: 11,
      faceoffPercentage: 47.62,
    },
    opponentStats: {
      goals: 11,
      assists: 8,
      points: 19,
      shots: 30,
      shootingPercentage: 36.67,
      shotsOnGoal: 23,
      shotsOnGoalPercentage: 76.67,
      groundBalls: 27,
      causedTurnovers: 9,
      turnovers: 11,
      saves: 8,
      goalsAllowed: 10,
      savePercentage: 44.44,
      faceoffsWon: 11,
      faceoffsLost: 10,
      faceoffPercentage: 52.38,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
  {
    date: '2024-09-12',
    opponentId: '4',
    teamScore: 15,
    opponentScore: 8,
    homeAway: 'home',
    teamsStats: {
      goals: 15,
      assists: 11,
      points: 26,
      shots: 38,
      shootingPercentage: 39.47,
      shotsOnGoal: 28,
      shotsOnGoalPercentage: 73.68,
      groundBalls: 32,
      causedTurnovers: 10,
      turnovers: 10,
      saves: 14,
      goalsAllowed: 8,
      savePercentage: 63.64,
      faceoffsWon: 15,
      faceoffsLost: 7,
      faceoffPercentage: 68.18,
    },
    opponentStats: {
      goals: 8,
      assists: 5,
      points: 13,
      shots: 22,
      shootingPercentage: 36.36,
      shotsOnGoal: 16,
      shotsOnGoalPercentage: 72.73,
      groundBalls: 20,
      causedTurnovers: 6,
      turnovers: 18,
      saves: 13,
      goalsAllowed: 15,
      savePercentage: 46.43,
      faceoffsWon: 7,
      faceoffsLost: 15,
      faceoffPercentage: 31.82,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
  {
    date: '2024-09-15',
    opponentId: '5',
    teamScore: 11,
    opponentScore: 10,
    homeAway: 'away',
    teamsStats: {
      goals: 11,
      assists: 8,
      points: 19,
      shots: 30,
      shootingPercentage: 36.67,
      shotsOnGoal: 20,
      shotsOnGoalPercentage: 66.67,
      groundBalls: 29,
      causedTurnovers: 8,
      turnovers: 13,
      saves: 16,
      goalsAllowed: 10,
      savePercentage: 61.54,
      faceoffsWon: 11,
      faceoffsLost: 10,
      faceoffPercentage: 52.38,
    },
    opponentStats: {
      goals: 10,
      assists: 7,
      points: 17,
      shots: 26,
      shootingPercentage: 38.46,
      shotsOnGoal: 19,
      shotsOnGoalPercentage: 73.08,
      groundBalls: 26,
      causedTurnovers: 7,
      turnovers: 14,
      saves: 9,
      goalsAllowed: 11,
      savePercentage: 45.0,
      faceoffsWon: 10,
      faceoffsLost: 11,
      faceoffPercentage: 47.62,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
  {
    date: '2024-09-19',
    opponentId: '6',
    teamScore: 14,
    opponentScore: 9,
    homeAway: 'home',
    teamsStats: {
      goals: 14,
      assists: 10,
      points: 24,
      shots: 35,
      shootingPercentage: 40.0,
      shotsOnGoal: 25,
      shotsOnGoalPercentage: 71.43,
      groundBalls: 30,
      causedTurnovers: 9,
      turnovers: 11,
      saves: 13,
      goalsAllowed: 9,
      savePercentage: 59.09,
      faceoffsWon: 13,
      faceoffsLost: 9,
      faceoffPercentage: 59.09,
    },
    opponentStats: {
      goals: 9,
      assists: 6,
      points: 15,
      shots: 22,
      shootingPercentage: 40.91,
      shotsOnGoal: 17,
      shotsOnGoalPercentage: 77.27,
      groundBalls: 24,
      causedTurnovers: 7,
      turnovers: 16,
      saves: 11,
      goalsAllowed: 14,
      savePercentage: 44.0,
      faceoffsWon: 9,
      faceoffsLost: 13,
      faceoffPercentage: 40.91,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
  {
    date: '2024-09-22',
    opponentId: '7',
    teamScore: 9,
    opponentScore: 12,
    homeAway: 'away',
    teamsStats: {
      goals: 9,
      assists: 6,
      points: 15,
      shots: 26,
      shootingPercentage: 34.62,
      shotsOnGoal: 17,
      shotsOnGoalPercentage: 65.38,
      groundBalls: 23,
      causedTurnovers: 6,
      turnovers: 15,
      saves: 15,
      goalsAllowed: 12,
      savePercentage: 55.56,
      faceoffsWon: 9,
      faceoffsLost: 12,
      faceoffPercentage: 42.86,
    },
    opponentStats: {
      goals: 12,
      assists: 9,
      points: 21,
      shots: 27,
      shootingPercentage: 44.44,
      shotsOnGoal: 21,
      shotsOnGoalPercentage: 77.78,
      groundBalls: 28,
      causedTurnovers: 10,
      turnovers: 12,
      saves: 8,
      goalsAllowed: 9,
      savePercentage: 47.06,
      faceoffsWon: 12,
      faceoffsLost: 9,
      faceoffPercentage: 57.14,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
  {
    date: '2024-09-26',
    opponentId: '8',
    teamScore: 13,
    opponentScore: 7,
    homeAway: 'home',
    teamsStats: {
      goals: 13,
      assists: 9,
      points: 22,
      shots: 33,
      shootingPercentage: 39.39,
      shotsOnGoal: 24,
      shotsOnGoalPercentage: 72.73,
      groundBalls: 31,
      causedTurnovers: 11,
      turnovers: 9,
      saves: 11,
      goalsAllowed: 7,
      savePercentage: 61.11,
      faceoffsWon: 14,
      faceoffsLost: 8,
      faceoffPercentage: 63.64,
    },
    opponentStats: {
      goals: 7,
      assists: 4,
      points: 11,
      shots: 18,
      shootingPercentage: 38.89,
      shotsOnGoal: 14,
      shotsOnGoalPercentage: 77.78,
      groundBalls: 19,
      causedTurnovers: 5,
      turnovers: 20,
      saves: 11,
      goalsAllowed: 13,
      savePercentage: 45.83,
      faceoffsWon: 8,
      faceoffsLost: 14,
      faceoffPercentage: 36.36,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
  {
    date: '2024-09-29',
    opponentId: '9',
    teamScore: 11,
    opponentScore: 11,
    homeAway: 'away',
    teamsStats: {
      goals: 11,
      assists: 8,
      points: 19,
      shots: 29,
      shootingPercentage: 37.93,
      shotsOnGoal: 20,
      shotsOnGoalPercentage: 68.97,
      groundBalls: 27,
      causedTurnovers: 7,
      turnovers: 14,
      saves: 14,
      goalsAllowed: 11,
      savePercentage: 56.0,
      faceoffsWon: 11,
      faceoffsLost: 11,
      faceoffPercentage: 50.0,
    },
    opponentStats: {
      goals: 11,
      assists: 8,
      points: 19,
      shots: 25,
      shootingPercentage: 44.0,
      shotsOnGoal: 19,
      shotsOnGoalPercentage: 76.0,
      groundBalls: 25,
      causedTurnovers: 8,
      turnovers: 13,
      saves: 9,
      goalsAllowed: 11,
      savePercentage: 45.0,
      faceoffsWon: 11,
      faceoffsLost: 11,
      faceoffPercentage: 50.0,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
  {
    date: '2024-10-03',
    opponentId: '10',
    teamScore: 16,
    opponentScore: 10,
    homeAway: 'home',
    teamsStats: {
      goals: 16,
      assists: 12,
      points: 28,
      shots: 40,
      shootingPercentage: 40.0,
      shotsOnGoal: 30,
      shotsOnGoalPercentage: 75.0,
      groundBalls: 35,
      causedTurnovers: 12,
      turnovers: 8,
      saves: 12,
      goalsAllowed: 10,
      savePercentage: 54.55,
      faceoffsWon: 16,
      faceoffsLost: 8,
      faceoffPercentage: 66.67,
    },
    opponentStats: {
      goals: 10,
      assists: 7,
      points: 17,
      shots: 22,
      shootingPercentage: 45.45,
      shotsOnGoal: 18,
      shotsOnGoalPercentage: 81.82,
      groundBalls: 21,
      causedTurnovers: 5,
      turnovers: 19,
      saves: 14,
      goalsAllowed: 16,
      savePercentage: 46.67,
      faceoffsWon: 8,
      faceoffsLost: 16,
      faceoffPercentage: 33.33,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
  {
    date: '2024-10-06',
    opponentId: '11',
    teamScore: 12,
    opponentScore: 11,
    homeAway: 'away',
    teamsStats: {
      goals: 12,
      assists: 9,
      points: 21,
      shots: 31,
      shootingPercentage: 38.71,
      shotsOnGoal: 22,
      shotsOnGoalPercentage: 70.97,
      groundBalls: 28,
      causedTurnovers: 8,
      turnovers: 12,
      saves: 15,
      goalsAllowed: 11,
      savePercentage: 57.69,
      faceoffsWon: 12,
      faceoffsLost: 10,
      faceoffPercentage: 54.55,
    },
    opponentStats: {
      goals: 11,
      assists: 8,
      points: 19,
      shots: 26,
      shootingPercentage: 42.31,
      shotsOnGoal: 20,
      shotsOnGoalPercentage: 76.92,
      groundBalls: 26,
      causedTurnovers: 7,
      turnovers: 14,
      saves: 10,
      goalsAllowed: 12,
      savePercentage: 45.45,
      faceoffsWon: 10,
      faceoffsLost: 12,
      faceoffPercentage: 45.45,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
  {
    date: '2024-10-10',
    opponentId: '12',
    teamScore: 10,
    opponentScore: 13,
    homeAway: 'home',
    teamsStats: {
      goals: 10,
      assists: 7,
      points: 17,
      shots: 27,
      shootingPercentage: 37.04,
      shotsOnGoal: 18,
      shotsOnGoalPercentage: 66.67,
      groundBalls: 24,
      causedTurnovers: 6,
      turnovers: 16,
      saves: 13,
      goalsAllowed: 13,
      savePercentage: 50.0,
      faceoffsWon: 10,
      faceoffsLost: 12,
      faceoffPercentage: 45.45,
    },
    opponentStats: {
      goals: 13,
      assists: 10,
      points: 23,
      shots: 26,
      shootingPercentage: 50.0,
      shotsOnGoal: 21,
      shotsOnGoalPercentage: 80.77,
      groundBalls: 29,
      causedTurnovers: 11,
      turnovers: 10,
      saves: 8,
      goalsAllowed: 10,
      savePercentage: 44.44,
      faceoffsWon: 12,
      faceoffsLost: 10,
      faceoffPercentage: 54.55,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
  {
    date: '2024-10-13',
    opponentId: '13',
    teamScore: 8,
    opponentScore: 9,
    homeAway: 'away',
    teamsStats: {
      goals: 8,
      assists: 5,
      points: 13,
      shots: 24,
      shootingPercentage: 33.33,
      shotsOnGoal: 15,
      shotsOnGoalPercentage: 62.5,
      groundBalls: 22,
      causedTurnovers: 5,
      turnovers: 17,
      saves: 16,
      goalsAllowed: 9,
      savePercentage: 64.0,
      faceoffsWon: 8,
      faceoffsLost: 13,
      faceoffPercentage: 38.1,
    },
    opponentStats: {
      goals: 9,
      assists: 6,
      points: 15,
      shots: 25,
      shootingPercentage: 36.0,
      shotsOnGoal: 19,
      shotsOnGoalPercentage: 76.0,
      groundBalls: 27,
      causedTurnovers: 10,
      turnovers: 11,
      saves: 7,
      goalsAllowed: 8,
      savePercentage: 46.67,
      faceoffsWon: 13,
      faceoffsLost: 8,
      faceoffPercentage: 61.9,
    },
    teamPlayerStats: new Array(8).fill(playerGameStats),
    opponentPlayerStats: new Array(8).fill(playerGameStats),
  },
];
