/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as ProtectedRedirectRouteImport } from './routes/_protected/redirect'
import { Route as ProtectedOrganizationSlugRouteImport } from './routes/_protected/$organizationSlug'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLogoutRouteImport } from './routes/(auth)/logout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProtectedOrganizationSlugIndexRouteImport } from './routes/_protected/$organizationSlug/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedOrganizationJoinRouteImport } from './routes/_protected/organization/join'
import { Route as ProtectedOrganizationCreateRouteImport } from './routes/_protected/organization/create'
import { Route as ProtectedOrganizationSlugFeedbackRouteImport } from './routes/_protected/$organizationSlug/feedback'
import { Route as ProtectedOrganizationSlugTeamIdRouteImport } from './routes/_protected/$organizationSlug/$teamId'
import { Route as ProtectedOrganizationSlugTeamIdIndexRouteImport } from './routes/_protected/$organizationSlug/$teamId/index'
import { Route as ProtectedOrganizationSlugTeamsCreateRouteImport } from './routes/_protected/$organizationSlug/teams.create'
import { Route as ProtectedOrganizationSlugOrganizationJoinRouteImport } from './routes/_protected/$organizationSlug/organization/join'
import { Route as ProtectedOrganizationSlugOrganizationCreateRouteImport } from './routes/_protected/$organizationSlug/organization/create'
import { Route as ProtectedOrganizationSlugTeamIdSetupRouteImport } from './routes/_protected/$organizationSlug/$teamId/setup'
import { Route as ProtectedOrganizationSlugTeamIdPlayersIndexRouteImport } from './routes/_protected/$organizationSlug/$teamId/players/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/(marketing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRedirectRoute = ProtectedRedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationSlugRoute =
  ProtectedOrganizationSlugRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => ProtectedRoute,
  } as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLogoutRoute = authLogoutRouteImport.update({
  id: '/(auth)/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrganizationSlugIndexRoute =
  ProtectedOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationSlugRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrganizationJoinRoute =
  ProtectedOrganizationJoinRouteImport.update({
    id: '/organization/join',
    path: '/organization/join',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrganizationCreateRoute =
  ProtectedOrganizationCreateRouteImport.update({
    id: '/organization/create',
    path: '/organization/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrganizationSlugFeedbackRoute =
  ProtectedOrganizationSlugFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => ProtectedOrganizationSlugRoute,
  } as any)
const ProtectedOrganizationSlugTeamIdRoute =
  ProtectedOrganizationSlugTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => ProtectedOrganizationSlugRoute,
  } as any)
const ProtectedOrganizationSlugTeamIdIndexRoute =
  ProtectedOrganizationSlugTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationSlugTeamIdRoute,
  } as any)
const ProtectedOrganizationSlugTeamsCreateRoute =
  ProtectedOrganizationSlugTeamsCreateRouteImport.update({
    id: '/teams/create',
    path: '/teams/create',
    getParentRoute: () => ProtectedOrganizationSlugRoute,
  } as any)
const ProtectedOrganizationSlugOrganizationJoinRoute =
  ProtectedOrganizationSlugOrganizationJoinRouteImport.update({
    id: '/organization/join',
    path: '/organization/join',
    getParentRoute: () => ProtectedOrganizationSlugRoute,
  } as any)
const ProtectedOrganizationSlugOrganizationCreateRoute =
  ProtectedOrganizationSlugOrganizationCreateRouteImport.update({
    id: '/organization/create',
    path: '/organization/create',
    getParentRoute: () => ProtectedOrganizationSlugRoute,
  } as any)
const ProtectedOrganizationSlugTeamIdSetupRoute =
  ProtectedOrganizationSlugTeamIdSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => ProtectedOrganizationSlugTeamIdRoute,
  } as any)
const ProtectedOrganizationSlugTeamIdPlayersIndexRoute =
  ProtectedOrganizationSlugTeamIdPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => ProtectedOrganizationSlugTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/test': typeof TestRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/register': typeof authRegisterRoute
  '/$organizationSlug': typeof ProtectedOrganizationSlugRouteWithChildren
  '/redirect': typeof ProtectedRedirectRoute
  '/': typeof marketingIndexRoute
  '/$organizationSlug/$teamId': typeof ProtectedOrganizationSlugTeamIdRouteWithChildren
  '/$organizationSlug/feedback': typeof ProtectedOrganizationSlugFeedbackRoute
  '/organization/create': typeof ProtectedOrganizationCreateRoute
  '/organization/join': typeof ProtectedOrganizationJoinRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$organizationSlug/': typeof ProtectedOrganizationSlugIndexRoute
  '/$organizationSlug/$teamId/setup': typeof ProtectedOrganizationSlugTeamIdSetupRoute
  '/$organizationSlug/organization/create': typeof ProtectedOrganizationSlugOrganizationCreateRoute
  '/$organizationSlug/organization/join': typeof ProtectedOrganizationSlugOrganizationJoinRoute
  '/$organizationSlug/teams/create': typeof ProtectedOrganizationSlugTeamsCreateRoute
  '/$organizationSlug/$teamId/': typeof ProtectedOrganizationSlugTeamIdIndexRoute
  '/$organizationSlug/$teamId/players': typeof ProtectedOrganizationSlugTeamIdPlayersIndexRoute
}
export interface FileRoutesByTo {
  '/test': typeof TestRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/register': typeof authRegisterRoute
  '/redirect': typeof ProtectedRedirectRoute
  '/': typeof marketingIndexRoute
  '/$organizationSlug/feedback': typeof ProtectedOrganizationSlugFeedbackRoute
  '/organization/create': typeof ProtectedOrganizationCreateRoute
  '/organization/join': typeof ProtectedOrganizationJoinRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$organizationSlug': typeof ProtectedOrganizationSlugIndexRoute
  '/$organizationSlug/$teamId/setup': typeof ProtectedOrganizationSlugTeamIdSetupRoute
  '/$organizationSlug/organization/create': typeof ProtectedOrganizationSlugOrganizationCreateRoute
  '/$organizationSlug/organization/join': typeof ProtectedOrganizationSlugOrganizationJoinRoute
  '/$organizationSlug/teams/create': typeof ProtectedOrganizationSlugTeamsCreateRoute
  '/$organizationSlug/$teamId': typeof ProtectedOrganizationSlugTeamIdIndexRoute
  '/$organizationSlug/$teamId/players': typeof ProtectedOrganizationSlugTeamIdPlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/test': typeof TestRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/logout': typeof authLogoutRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_protected/$organizationSlug': typeof ProtectedOrganizationSlugRouteWithChildren
  '/_protected/redirect': typeof ProtectedRedirectRoute
  '/(marketing)/': typeof marketingIndexRoute
  '/_protected/$organizationSlug/$teamId': typeof ProtectedOrganizationSlugTeamIdRouteWithChildren
  '/_protected/$organizationSlug/feedback': typeof ProtectedOrganizationSlugFeedbackRoute
  '/_protected/organization/create': typeof ProtectedOrganizationCreateRoute
  '/_protected/organization/join': typeof ProtectedOrganizationJoinRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/$organizationSlug/': typeof ProtectedOrganizationSlugIndexRoute
  '/_protected/$organizationSlug/$teamId/setup': typeof ProtectedOrganizationSlugTeamIdSetupRoute
  '/_protected/$organizationSlug/organization/create': typeof ProtectedOrganizationSlugOrganizationCreateRoute
  '/_protected/$organizationSlug/organization/join': typeof ProtectedOrganizationSlugOrganizationJoinRoute
  '/_protected/$organizationSlug/teams/create': typeof ProtectedOrganizationSlugTeamsCreateRoute
  '/_protected/$organizationSlug/$teamId/': typeof ProtectedOrganizationSlugTeamIdIndexRoute
  '/_protected/$organizationSlug/$teamId/players/': typeof ProtectedOrganizationSlugTeamIdPlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/test'
    | '/login'
    | '/logout'
    | '/register'
    | '/$organizationSlug'
    | '/redirect'
    | '/'
    | '/$organizationSlug/$teamId'
    | '/$organizationSlug/feedback'
    | '/organization/create'
    | '/organization/join'
    | '/api/auth/$'
    | '/$organizationSlug/'
    | '/$organizationSlug/$teamId/setup'
    | '/$organizationSlug/organization/create'
    | '/$organizationSlug/organization/join'
    | '/$organizationSlug/teams/create'
    | '/$organizationSlug/$teamId/'
    | '/$organizationSlug/$teamId/players'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/test'
    | '/login'
    | '/logout'
    | '/register'
    | '/redirect'
    | '/'
    | '/$organizationSlug/feedback'
    | '/organization/create'
    | '/organization/join'
    | '/api/auth/$'
    | '/$organizationSlug'
    | '/$organizationSlug/$teamId/setup'
    | '/$organizationSlug/organization/create'
    | '/$organizationSlug/organization/join'
    | '/$organizationSlug/teams/create'
    | '/$organizationSlug/$teamId'
    | '/$organizationSlug/$teamId/players'
  id:
    | '__root__'
    | '/_protected'
    | '/test'
    | '/(auth)/login'
    | '/(auth)/logout'
    | '/(auth)/register'
    | '/_protected/$organizationSlug'
    | '/_protected/redirect'
    | '/(marketing)/'
    | '/_protected/$organizationSlug/$teamId'
    | '/_protected/$organizationSlug/feedback'
    | '/_protected/organization/create'
    | '/_protected/organization/join'
    | '/api/auth/$'
    | '/_protected/$organizationSlug/'
    | '/_protected/$organizationSlug/$teamId/setup'
    | '/_protected/$organizationSlug/organization/create'
    | '/_protected/$organizationSlug/organization/join'
    | '/_protected/$organizationSlug/teams/create'
    | '/_protected/$organizationSlug/$teamId/'
    | '/_protected/$organizationSlug/$teamId/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  TestRoute: typeof TestRoute
  authLoginRoute: typeof authLoginRoute
  authLogoutRoute: typeof authLogoutRoute
  authRegisterRoute: typeof authRegisterRoute
  marketingIndexRoute: typeof marketingIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/redirect': {
      id: '/_protected/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof ProtectedRedirectRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$organizationSlug': {
      id: '/_protected/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof ProtectedOrganizationSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/logout': {
      id: '/(auth)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/$organizationSlug/': {
      id: '/_protected/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof ProtectedOrganizationSlugIndexRouteImport
      parentRoute: typeof ProtectedOrganizationSlugRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/organization/join': {
      id: '/_protected/organization/join'
      path: '/organization/join'
      fullPath: '/organization/join'
      preLoaderRoute: typeof ProtectedOrganizationJoinRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organization/create': {
      id: '/_protected/organization/create'
      path: '/organization/create'
      fullPath: '/organization/create'
      preLoaderRoute: typeof ProtectedOrganizationCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$organizationSlug/feedback': {
      id: '/_protected/$organizationSlug/feedback'
      path: '/feedback'
      fullPath: '/$organizationSlug/feedback'
      preLoaderRoute: typeof ProtectedOrganizationSlugFeedbackRouteImport
      parentRoute: typeof ProtectedOrganizationSlugRoute
    }
    '/_protected/$organizationSlug/$teamId': {
      id: '/_protected/$organizationSlug/$teamId'
      path: '/$teamId'
      fullPath: '/$organizationSlug/$teamId'
      preLoaderRoute: typeof ProtectedOrganizationSlugTeamIdRouteImport
      parentRoute: typeof ProtectedOrganizationSlugRoute
    }
    '/_protected/$organizationSlug/$teamId/': {
      id: '/_protected/$organizationSlug/$teamId/'
      path: '/'
      fullPath: '/$organizationSlug/$teamId/'
      preLoaderRoute: typeof ProtectedOrganizationSlugTeamIdIndexRouteImport
      parentRoute: typeof ProtectedOrganizationSlugTeamIdRoute
    }
    '/_protected/$organizationSlug/teams/create': {
      id: '/_protected/$organizationSlug/teams/create'
      path: '/teams/create'
      fullPath: '/$organizationSlug/teams/create'
      preLoaderRoute: typeof ProtectedOrganizationSlugTeamsCreateRouteImport
      parentRoute: typeof ProtectedOrganizationSlugRoute
    }
    '/_protected/$organizationSlug/organization/join': {
      id: '/_protected/$organizationSlug/organization/join'
      path: '/organization/join'
      fullPath: '/$organizationSlug/organization/join'
      preLoaderRoute: typeof ProtectedOrganizationSlugOrganizationJoinRouteImport
      parentRoute: typeof ProtectedOrganizationSlugRoute
    }
    '/_protected/$organizationSlug/organization/create': {
      id: '/_protected/$organizationSlug/organization/create'
      path: '/organization/create'
      fullPath: '/$organizationSlug/organization/create'
      preLoaderRoute: typeof ProtectedOrganizationSlugOrganizationCreateRouteImport
      parentRoute: typeof ProtectedOrganizationSlugRoute
    }
    '/_protected/$organizationSlug/$teamId/setup': {
      id: '/_protected/$organizationSlug/$teamId/setup'
      path: '/setup'
      fullPath: '/$organizationSlug/$teamId/setup'
      preLoaderRoute: typeof ProtectedOrganizationSlugTeamIdSetupRouteImport
      parentRoute: typeof ProtectedOrganizationSlugTeamIdRoute
    }
    '/_protected/$organizationSlug/$teamId/players/': {
      id: '/_protected/$organizationSlug/$teamId/players/'
      path: '/players'
      fullPath: '/$organizationSlug/$teamId/players'
      preLoaderRoute: typeof ProtectedOrganizationSlugTeamIdPlayersIndexRouteImport
      parentRoute: typeof ProtectedOrganizationSlugTeamIdRoute
    }
  }
}

interface ProtectedOrganizationSlugTeamIdRouteChildren {
  ProtectedOrganizationSlugTeamIdSetupRoute: typeof ProtectedOrganizationSlugTeamIdSetupRoute
  ProtectedOrganizationSlugTeamIdIndexRoute: typeof ProtectedOrganizationSlugTeamIdIndexRoute
  ProtectedOrganizationSlugTeamIdPlayersIndexRoute: typeof ProtectedOrganizationSlugTeamIdPlayersIndexRoute
}

const ProtectedOrganizationSlugTeamIdRouteChildren: ProtectedOrganizationSlugTeamIdRouteChildren =
  {
    ProtectedOrganizationSlugTeamIdSetupRoute:
      ProtectedOrganizationSlugTeamIdSetupRoute,
    ProtectedOrganizationSlugTeamIdIndexRoute:
      ProtectedOrganizationSlugTeamIdIndexRoute,
    ProtectedOrganizationSlugTeamIdPlayersIndexRoute:
      ProtectedOrganizationSlugTeamIdPlayersIndexRoute,
  }

const ProtectedOrganizationSlugTeamIdRouteWithChildren =
  ProtectedOrganizationSlugTeamIdRoute._addFileChildren(
    ProtectedOrganizationSlugTeamIdRouteChildren,
  )

interface ProtectedOrganizationSlugRouteChildren {
  ProtectedOrganizationSlugTeamIdRoute: typeof ProtectedOrganizationSlugTeamIdRouteWithChildren
  ProtectedOrganizationSlugFeedbackRoute: typeof ProtectedOrganizationSlugFeedbackRoute
  ProtectedOrganizationSlugIndexRoute: typeof ProtectedOrganizationSlugIndexRoute
  ProtectedOrganizationSlugOrganizationCreateRoute: typeof ProtectedOrganizationSlugOrganizationCreateRoute
  ProtectedOrganizationSlugOrganizationJoinRoute: typeof ProtectedOrganizationSlugOrganizationJoinRoute
  ProtectedOrganizationSlugTeamsCreateRoute: typeof ProtectedOrganizationSlugTeamsCreateRoute
}

const ProtectedOrganizationSlugRouteChildren: ProtectedOrganizationSlugRouteChildren =
  {
    ProtectedOrganizationSlugTeamIdRoute:
      ProtectedOrganizationSlugTeamIdRouteWithChildren,
    ProtectedOrganizationSlugFeedbackRoute:
      ProtectedOrganizationSlugFeedbackRoute,
    ProtectedOrganizationSlugIndexRoute: ProtectedOrganizationSlugIndexRoute,
    ProtectedOrganizationSlugOrganizationCreateRoute:
      ProtectedOrganizationSlugOrganizationCreateRoute,
    ProtectedOrganizationSlugOrganizationJoinRoute:
      ProtectedOrganizationSlugOrganizationJoinRoute,
    ProtectedOrganizationSlugTeamsCreateRoute:
      ProtectedOrganizationSlugTeamsCreateRoute,
  }

const ProtectedOrganizationSlugRouteWithChildren =
  ProtectedOrganizationSlugRoute._addFileChildren(
    ProtectedOrganizationSlugRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedOrganizationSlugRoute: typeof ProtectedOrganizationSlugRouteWithChildren
  ProtectedRedirectRoute: typeof ProtectedRedirectRoute
  ProtectedOrganizationCreateRoute: typeof ProtectedOrganizationCreateRoute
  ProtectedOrganizationJoinRoute: typeof ProtectedOrganizationJoinRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedOrganizationSlugRoute: ProtectedOrganizationSlugRouteWithChildren,
  ProtectedRedirectRoute: ProtectedRedirectRoute,
  ProtectedOrganizationCreateRoute: ProtectedOrganizationCreateRoute,
  ProtectedOrganizationJoinRoute: ProtectedOrganizationJoinRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  TestRoute: TestRoute,
  authLoginRoute: authLoginRoute,
  authLogoutRoute: authLogoutRoute,
  authRegisterRoute: authRegisterRoute,
  marketingIndexRoute: marketingIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
