/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as AppRosterRouteImport } from './routes/_app/roster'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPlayerRouteImport } from './routes/_app/player'
import { Route as AppPhotosRouteImport } from './routes/_app/photos'
import { Route as AppFixturesRouteImport } from './routes/_app/fixtures'
import { Route as AppFinesRouteImport } from './routes/_app/fines'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as ApiReportImagesImageIdRouteImport } from './routes/api/report-images/$imageId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppTeamsTeamIdRouteImport } from './routes/_app/teams/$teamId'
import { Route as AppTeamsTeamIdStatsRouteImport } from './routes/_app/teams/$teamId_.stats'
import { Route as AppTeamsTeamIdStandingsRouteImport } from './routes/_app/teams/$teamId_.standings'
import { Route as AppTeamsTeamIdRosterRouteImport } from './routes/_app/teams/$teamId_.roster'
import { Route as AppTeamsTeamIdReportsRouteImport } from './routes/_app/teams/$teamId_.reports'
import { Route as AppTeamsTeamIdPhotosRouteImport } from './routes/_app/teams/$teamId_.photos'
import { Route as AppTeamsTeamIdFixturesRouteImport } from './routes/_app/teams/$teamId_.fixtures'
import { Route as AppTeamsTeamIdFixturesFixtureIdRouteImport } from './routes/_app/teams/$teamId_.fixtures_/$fixtureId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRosterRoute = AppRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayerRoute = AppPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => AppRoute,
} as any)
const AppPhotosRoute = AppPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AppRoute,
} as any)
const AppFixturesRoute = AppFixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => AppRoute,
} as any)
const AppFinesRoute = AppFinesRouteImport.update({
  id: '/fines',
  path: '/fines',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppRoute,
} as any)
const ApiReportImagesImageIdRoute = ApiReportImagesImageIdRouteImport.update({
  id: '/api/report-images/$imageId',
  path: '/api/report-images/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdStatsRoute = AppTeamsTeamIdStatsRouteImport.update({
  id: '/teams/$teamId_/stats',
  path: '/teams/$teamId/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdStandingsRoute = AppTeamsTeamIdStandingsRouteImport.update({
  id: '/teams/$teamId_/standings',
  path: '/teams/$teamId/standings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdRosterRoute = AppTeamsTeamIdRosterRouteImport.update({
  id: '/teams/$teamId_/roster',
  path: '/teams/$teamId/roster',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdReportsRoute = AppTeamsTeamIdReportsRouteImport.update({
  id: '/teams/$teamId_/reports',
  path: '/teams/$teamId/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdPhotosRoute = AppTeamsTeamIdPhotosRouteImport.update({
  id: '/teams/$teamId_/photos',
  path: '/teams/$teamId/photos',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdFixturesRoute = AppTeamsTeamIdFixturesRouteImport.update({
  id: '/teams/$teamId_/fixtures',
  path: '/teams/$teamId/fixtures',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdFixturesFixtureIdRoute =
  AppTeamsTeamIdFixturesFixtureIdRouteImport.update({
    id: '/teams/$teamId_/fixtures_/$fixtureId',
    path: '/teams/$teamId/fixtures/$fixtureId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/audit': typeof AppAuditRoute
  '/fines': typeof AppFinesRoute
  '/fixtures': typeof AppFixturesRoute
  '/photos': typeof AppPhotosRoute
  '/player': typeof AppPlayerRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/roster': typeof AppRosterRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/report-images/$imageId': typeof ApiReportImagesImageIdRoute
  '/teams/': typeof AppTeamsIndexRoute
  '/teams/$teamId/fixtures': typeof AppTeamsTeamIdFixturesRoute
  '/teams/$teamId/photos': typeof AppTeamsTeamIdPhotosRoute
  '/teams/$teamId/reports': typeof AppTeamsTeamIdReportsRoute
  '/teams/$teamId/roster': typeof AppTeamsTeamIdRosterRoute
  '/teams/$teamId/standings': typeof AppTeamsTeamIdStandingsRoute
  '/teams/$teamId/stats': typeof AppTeamsTeamIdStatsRoute
  '/teams/$teamId/fixtures/$fixtureId': typeof AppTeamsTeamIdFixturesFixtureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/audit': typeof AppAuditRoute
  '/fines': typeof AppFinesRoute
  '/fixtures': typeof AppFixturesRoute
  '/photos': typeof AppPhotosRoute
  '/player': typeof AppPlayerRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/roster': typeof AppRosterRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/report-images/$imageId': typeof ApiReportImagesImageIdRoute
  '/teams': typeof AppTeamsIndexRoute
  '/teams/$teamId/fixtures': typeof AppTeamsTeamIdFixturesRoute
  '/teams/$teamId/photos': typeof AppTeamsTeamIdPhotosRoute
  '/teams/$teamId/reports': typeof AppTeamsTeamIdReportsRoute
  '/teams/$teamId/roster': typeof AppTeamsTeamIdRosterRoute
  '/teams/$teamId/standings': typeof AppTeamsTeamIdStandingsRoute
  '/teams/$teamId/stats': typeof AppTeamsTeamIdStatsRoute
  '/teams/$teamId/fixtures/$fixtureId': typeof AppTeamsTeamIdFixturesFixtureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/fines': typeof AppFinesRoute
  '/_app/fixtures': typeof AppFixturesRoute
  '/_app/photos': typeof AppPhotosRoute
  '/_app/player': typeof AppPlayerRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roster': typeof AppRosterRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/report-images/$imageId': typeof ApiReportImagesImageIdRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
  '/_app/teams/$teamId_/fixtures': typeof AppTeamsTeamIdFixturesRoute
  '/_app/teams/$teamId_/photos': typeof AppTeamsTeamIdPhotosRoute
  '/_app/teams/$teamId_/reports': typeof AppTeamsTeamIdReportsRoute
  '/_app/teams/$teamId_/roster': typeof AppTeamsTeamIdRosterRoute
  '/_app/teams/$teamId_/standings': typeof AppTeamsTeamIdStandingsRoute
  '/_app/teams/$teamId_/stats': typeof AppTeamsTeamIdStatsRoute
  '/_app/teams/$teamId_/fixtures_/$fixtureId': typeof AppTeamsTeamIdFixturesFixtureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/audit'
    | '/fines'
    | '/fixtures'
    | '/photos'
    | '/player'
    | '/profile'
    | '/reports'
    | '/roster'
    | '/accept-invitation/$id'
    | '/teams/$teamId'
    | '/api/auth/$'
    | '/api/report-images/$imageId'
    | '/teams/'
    | '/teams/$teamId/fixtures'
    | '/teams/$teamId/photos'
    | '/teams/$teamId/reports'
    | '/teams/$teamId/roster'
    | '/teams/$teamId/standings'
    | '/teams/$teamId/stats'
    | '/teams/$teamId/fixtures/$fixtureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/audit'
    | '/fines'
    | '/fixtures'
    | '/photos'
    | '/player'
    | '/profile'
    | '/reports'
    | '/roster'
    | '/accept-invitation/$id'
    | '/teams/$teamId'
    | '/api/auth/$'
    | '/api/report-images/$imageId'
    | '/teams'
    | '/teams/$teamId/fixtures'
    | '/teams/$teamId/photos'
    | '/teams/$teamId/reports'
    | '/teams/$teamId/roster'
    | '/teams/$teamId/standings'
    | '/teams/$teamId/stats'
    | '/teams/$teamId/fixtures/$fixtureId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/audit'
    | '/_app/fines'
    | '/_app/fixtures'
    | '/_app/photos'
    | '/_app/player'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/roster'
    | '/accept-invitation/$id'
    | '/_app/teams/$teamId'
    | '/api/auth/$'
    | '/api/report-images/$imageId'
    | '/_app/teams/'
    | '/_app/teams/$teamId_/fixtures'
    | '/_app/teams/$teamId_/photos'
    | '/_app/teams/$teamId_/reports'
    | '/_app/teams/$teamId_/roster'
    | '/_app/teams/$teamId_/standings'
    | '/_app/teams/$teamId_/stats'
    | '/_app/teams/$teamId_/fixtures_/$fixtureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiReportImagesImageIdRoute: typeof ApiReportImagesImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/roster': {
      id: '/_app/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AppRosterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/player': {
      id: '/_app/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof AppPlayerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/photos': {
      id: '/_app/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof AppPhotosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fixtures': {
      id: '/_app/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof AppFixturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fines': {
      id: '/_app/fines'
      path: '/fines'
      fullPath: '/fines'
      preLoaderRoute: typeof AppFinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/report-images/$imageId': {
      id: '/api/report-images/$imageId'
      path: '/api/report-images/$imageId'
      fullPath: '/api/report-images/$imageId'
      preLoaderRoute: typeof ApiReportImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId_/stats': {
      id: '/_app/teams/$teamId_/stats'
      path: '/teams/$teamId/stats'
      fullPath: '/teams/$teamId/stats'
      preLoaderRoute: typeof AppTeamsTeamIdStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId_/standings': {
      id: '/_app/teams/$teamId_/standings'
      path: '/teams/$teamId/standings'
      fullPath: '/teams/$teamId/standings'
      preLoaderRoute: typeof AppTeamsTeamIdStandingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId_/roster': {
      id: '/_app/teams/$teamId_/roster'
      path: '/teams/$teamId/roster'
      fullPath: '/teams/$teamId/roster'
      preLoaderRoute: typeof AppTeamsTeamIdRosterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId_/reports': {
      id: '/_app/teams/$teamId_/reports'
      path: '/teams/$teamId/reports'
      fullPath: '/teams/$teamId/reports'
      preLoaderRoute: typeof AppTeamsTeamIdReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId_/photos': {
      id: '/_app/teams/$teamId_/photos'
      path: '/teams/$teamId/photos'
      fullPath: '/teams/$teamId/photos'
      preLoaderRoute: typeof AppTeamsTeamIdPhotosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId_/fixtures': {
      id: '/_app/teams/$teamId_/fixtures'
      path: '/teams/$teamId/fixtures'
      fullPath: '/teams/$teamId/fixtures'
      preLoaderRoute: typeof AppTeamsTeamIdFixturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId_/fixtures_/$fixtureId': {
      id: '/_app/teams/$teamId_/fixtures_/$fixtureId'
      path: '/teams/$teamId/fixtures/$fixtureId'
      fullPath: '/teams/$teamId/fixtures/$fixtureId'
      preLoaderRoute: typeof AppTeamsTeamIdFixturesFixtureIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuditRoute: typeof AppAuditRoute
  AppFinesRoute: typeof AppFinesRoute
  AppFixturesRoute: typeof AppFixturesRoute
  AppPhotosRoute: typeof AppPhotosRoute
  AppPlayerRoute: typeof AppPlayerRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRosterRoute: typeof AppRosterRoute
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
  AppTeamsTeamIdFixturesRoute: typeof AppTeamsTeamIdFixturesRoute
  AppTeamsTeamIdPhotosRoute: typeof AppTeamsTeamIdPhotosRoute
  AppTeamsTeamIdReportsRoute: typeof AppTeamsTeamIdReportsRoute
  AppTeamsTeamIdRosterRoute: typeof AppTeamsTeamIdRosterRoute
  AppTeamsTeamIdStandingsRoute: typeof AppTeamsTeamIdStandingsRoute
  AppTeamsTeamIdStatsRoute: typeof AppTeamsTeamIdStatsRoute
  AppTeamsTeamIdFixturesFixtureIdRoute: typeof AppTeamsTeamIdFixturesFixtureIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuditRoute: AppAuditRoute,
  AppFinesRoute: AppFinesRoute,
  AppFixturesRoute: AppFixturesRoute,
  AppPhotosRoute: AppPhotosRoute,
  AppPlayerRoute: AppPlayerRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppRosterRoute: AppRosterRoute,
  AppTeamsTeamIdRoute: AppTeamsTeamIdRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
  AppTeamsTeamIdFixturesRoute: AppTeamsTeamIdFixturesRoute,
  AppTeamsTeamIdPhotosRoute: AppTeamsTeamIdPhotosRoute,
  AppTeamsTeamIdReportsRoute: AppTeamsTeamIdReportsRoute,
  AppTeamsTeamIdRosterRoute: AppTeamsTeamIdRosterRoute,
  AppTeamsTeamIdStandingsRoute: AppTeamsTeamIdStandingsRoute,
  AppTeamsTeamIdStatsRoute: AppTeamsTeamIdStatsRoute,
  AppTeamsTeamIdFixturesFixtureIdRoute: AppTeamsTeamIdFixturesFixtureIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiReportImagesImageIdRoute: ApiReportImagesImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
