/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as AppRosterRouteImport } from './routes/_app/roster'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPlayerRouteImport } from './routes/_app/player'
import { Route as AppFixturesRouteImport } from './routes/_app/fixtures'
import { Route as AppFinesRouteImport } from './routes/_app/fines'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as ApiReportImagesImageIdRouteImport } from './routes/api/report-images/$imageId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppReportFixtureIdRouteImport } from './routes/_app/report/$fixtureId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRosterRoute = AppRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayerRoute = AppPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => AppRoute,
} as any)
const AppFixturesRoute = AppFixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => AppRoute,
} as any)
const AppFinesRoute = AppFinesRouteImport.update({
  id: '/fines',
  path: '/fines',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiReportImagesImageIdRoute = ApiReportImagesImageIdRouteImport.update({
  id: '/api/report-images/$imageId',
  path: '/api/report-images/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportFixtureIdRoute = AppReportFixtureIdRouteImport.update({
  id: '/report/$fixtureId',
  path: '/report/$fixtureId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/audit': typeof AppAuditRoute
  '/fines': typeof AppFinesRoute
  '/fixtures': typeof AppFixturesRoute
  '/player': typeof AppPlayerRoute
  '/profile': typeof AppProfileRoute
  '/roster': typeof AppRosterRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/report/$fixtureId': typeof AppReportFixtureIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/report-images/$imageId': typeof ApiReportImagesImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/audit': typeof AppAuditRoute
  '/fines': typeof AppFinesRoute
  '/fixtures': typeof AppFixturesRoute
  '/player': typeof AppPlayerRoute
  '/profile': typeof AppProfileRoute
  '/roster': typeof AppRosterRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/report/$fixtureId': typeof AppReportFixtureIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/report-images/$imageId': typeof ApiReportImagesImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/fines': typeof AppFinesRoute
  '/_app/fixtures': typeof AppFixturesRoute
  '/_app/player': typeof AppPlayerRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/roster': typeof AppRosterRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/_app/report/$fixtureId': typeof AppReportFixtureIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/report-images/$imageId': typeof ApiReportImagesImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/audit'
    | '/fines'
    | '/fixtures'
    | '/player'
    | '/profile'
    | '/roster'
    | '/accept-invitation/$id'
    | '/report/$fixtureId'
    | '/api/auth/$'
    | '/api/report-images/$imageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/audit'
    | '/fines'
    | '/fixtures'
    | '/player'
    | '/profile'
    | '/roster'
    | '/accept-invitation/$id'
    | '/report/$fixtureId'
    | '/api/auth/$'
    | '/api/report-images/$imageId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/audit'
    | '/_app/fines'
    | '/_app/fixtures'
    | '/_app/player'
    | '/_app/profile'
    | '/_app/roster'
    | '/accept-invitation/$id'
    | '/_app/report/$fixtureId'
    | '/api/auth/$'
    | '/api/report-images/$imageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiReportImagesImageIdRoute: typeof ApiReportImagesImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/roster': {
      id: '/_app/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AppRosterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/player': {
      id: '/_app/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof AppPlayerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fixtures': {
      id: '/_app/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof AppFixturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fines': {
      id: '/_app/fines'
      path: '/fines'
      fullPath: '/fines'
      preLoaderRoute: typeof AppFinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/report-images/$imageId': {
      id: '/api/report-images/$imageId'
      path: '/api/report-images/$imageId'
      fullPath: '/api/report-images/$imageId'
      preLoaderRoute: typeof ApiReportImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/report/$fixtureId': {
      id: '/_app/report/$fixtureId'
      path: '/report/$fixtureId'
      fullPath: '/report/$fixtureId'
      preLoaderRoute: typeof AppReportFixtureIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuditRoute: typeof AppAuditRoute
  AppFinesRoute: typeof AppFinesRoute
  AppFixturesRoute: typeof AppFixturesRoute
  AppPlayerRoute: typeof AppPlayerRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRosterRoute: typeof AppRosterRoute
  AppReportFixtureIdRoute: typeof AppReportFixtureIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuditRoute: AppAuditRoute,
  AppFinesRoute: AppFinesRoute,
  AppFixturesRoute: AppFixturesRoute,
  AppPlayerRoute: AppPlayerRoute,
  AppProfileRoute: AppProfileRoute,
  AppRosterRoute: AppRosterRoute,
  AppReportFixtureIdRoute: AppReportFixtureIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiReportImagesImageIdRoute: ApiReportImagesImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
