export const CLI_ENTRYPOINTS = [
  "defaults",
  "drill",
  "play",
  "player",
  "practice",
] as const;

// Must stay alphabetically sorted and be updated whenever a new HTTP API
// endpoint is intentionally exposed through the CLI. coverage.test.ts enforces
// both.
export const CLI_HTTP_COVERAGE = [
  "addPracticeItem",
  "adjustFine",
  "createDrill",
  "createPlay",
  "createPlayer",
  "createPractice",
  "createPracticeReview",
  "createTemplate",
  "deleteDrill",
  "deletePlay",
  "deletePlayer",
  "deletePractice",
  "deleteTemplate",
  "forgiveFine",
  "getDrill",
  "getNamespace",
  "getPlay",
  "getPlayer",
  "getPractice",
  "getPracticeReview",
  "issueFine",
  "listAudit",
  "listDrills",
  "listFineEvents",
  "listFines",
  "listMemberFines",
  "listMembers",
  "listPlayers",
  "listPlays",
  "listPracticeEdges",
  "listPracticeItems",
  "listPractices",
  "listTemplates",
  "me",
  "patchNamespace",
  "payFine",
  "removePracticeItem",
  "reorderPracticeItems",
  "replacePracticeEdges",
  "updateDrill",
  "updatePlay",
  "updatePlayer",
  "updatePractice",
  "updatePracticeItem",
  "updatePracticeReview",
  "updateTemplate",
] as const;
