export const CLI_ENTRYPOINTS = [
  "defaults",
  "drill",
  "play",
  "player",
  "practice",
] as const;

// Must stay alphabetically sorted and be updated whenever a new API RPC is
// intentionally exposed through the CLI. coverage.test.ts enforces both.
export const CLI_RPC_COVERAGE = [
  "DefaultsGetNamespace",
  "DefaultsPatchNamespace",
  "DrillCreate",
  "DrillDelete",
  "DrillGet",
  "DrillList",
  "DrillUpdate",
  "PlayCreate",
  "PlayDelete",
  "PlayGet",
  "PlayList",
  "PlayUpdate",
  "PlayerCreate",
  "PlayerDelete",
  "PlayerGet",
  "PlayerList",
  "PlayerUpdate",
  "PracticeAddItem",
  "PracticeCreate",
  "PracticeCreateReview",
  "PracticeDelete",
  "PracticeGet",
  "PracticeGetReview",
  "PracticeList",
  "PracticeListEdges",
  "PracticeListItems",
  "PracticeRemoveItem",
  "PracticeReorderItems",
  "PracticeReplaceEdges",
  "PracticeUpdate",
  "PracticeUpdateItem",
  "PracticeUpdateReview",
] as const;
