/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaybookIndexRouteImport } from './routes/playbook/index'
import { Route as PracticeIdRouteImport } from './routes/practice/$id'
import { Route as PlaybookNewRouteImport } from './routes/playbook/new'
import { Route as PlaybookIdRouteImport } from './routes/playbook/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookIndexRoute = PlaybookIndexRouteImport.update({
  id: '/playbook/',
  path: '/playbook/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIdRoute = PracticeIdRouteImport.update({
  id: '/practice/$id',
  path: '/practice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookNewRoute = PlaybookNewRouteImport.update({
  id: '/playbook/new',
  path: '/playbook/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookIdRoute = PlaybookIdRouteImport.update({
  id: '/playbook/$id',
  path: '/playbook/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playbook/$id': typeof PlaybookIdRoute
  '/playbook/new': typeof PlaybookNewRoute
  '/practice/$id': typeof PracticeIdRoute
  '/playbook/': typeof PlaybookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playbook/$id': typeof PlaybookIdRoute
  '/playbook/new': typeof PlaybookNewRoute
  '/practice/$id': typeof PracticeIdRoute
  '/playbook': typeof PlaybookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playbook/$id': typeof PlaybookIdRoute
  '/playbook/new': typeof PlaybookNewRoute
  '/practice/$id': typeof PracticeIdRoute
  '/playbook/': typeof PlaybookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playbook/$id'
    | '/playbook/new'
    | '/practice/$id'
    | '/playbook/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/playbook/$id' | '/playbook/new' | '/practice/$id' | '/playbook'
  id:
    | '__root__'
    | '/'
    | '/playbook/$id'
    | '/playbook/new'
    | '/practice/$id'
    | '/playbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaybookIdRoute: typeof PlaybookIdRoute
  PlaybookNewRoute: typeof PlaybookNewRoute
  PracticeIdRoute: typeof PracticeIdRoute
  PlaybookIndexRoute: typeof PlaybookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/': {
      id: '/playbook/'
      path: '/playbook'
      fullPath: '/playbook/'
      preLoaderRoute: typeof PlaybookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$id': {
      id: '/practice/$id'
      path: '/practice/$id'
      fullPath: '/practice/$id'
      preLoaderRoute: typeof PracticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/new': {
      id: '/playbook/new'
      path: '/playbook/new'
      fullPath: '/playbook/new'
      preLoaderRoute: typeof PlaybookNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/$id': {
      id: '/playbook/$id'
      path: '/playbook/$id'
      fullPath: '/playbook/$id'
      preLoaderRoute: typeof PlaybookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaybookIdRoute: PlaybookIdRoute,
  PlaybookNewRoute: PlaybookNewRoute,
  PracticeIdRoute: PracticeIdRoute,
  PlaybookIndexRoute: PlaybookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
